### ISSUE TITLE
Can't use URL helpers in swagger_root

### ISSUE THREAD

**Issue by xtagon** [fotinakis/swagger-blocks#2] opened 2014-11-26 17:52 UTC
Hi,

I'm trying to add OAuth authorization to my Swagger resource listing with Swagger-Blocks. In order to do this I need to use the route helpers so I can get the correct `oauth_authorization_url` in each Rails environment. In most parts of my application I can call Rails.application.routes.url_helpers.oauth_authorization_url. However, it does not work within any child of the `swagger_root` block in my base controller class. I get the following error:

    in `<class:BaseController>': undefined method `oauth_authorization_url' for #<Module:0x007fe2140e4590> (NoMethodError)

Any help would be greatly appreciated.

Regards,
Justin

**Comment by fotinakis** [comment] 2015-01-17 01:12
Hey @xtagon — sorry for the delay, found a minute to look into this.

I couldn't reproduce this, this worked fine inside the controller:
```
  include Swagger::Blocks

  swagger_api_root :pets do
    key :swaggerVersion, '1.2'
    key :apiVersion, '1.0.0'
    key :basePath, Rails.application.routes.url_helpers.pets_path
  end
```
...and the correct JSON was generated. I was only able to generate the error you mentioned if my _path helper name was wrong. Can you check if that is correct for you?

I'm going to close this since it can't be reproduced, feel free to re-open with a specific code snippet that fails. Thanks!

**Closed by fotinakis** 2015-01-17 01:12 UTC

**Comment by avitus** [comment] 2016-02-12 00:24
I think what OP meant was that in the Swagger docs there is often a URL which doesn't conform to the rest of the API. For instance, in our case we have 

/oauth/token
/1/users
/1/translations
/1/...

This is a result of using Doorkeeper gem for the oauth part and rocket_pants gem for everything else.

We would still like to have /oauth/token documented but there doesn't seem to be a way to omit the insertion of the basePath (which in this case is /1/)
